"""Explicit, reviewable prompt templates — kept out of agent/service code
so prompt-engineering changes are a one-file diff.

Every template instructs the model to ground its answer strictly in the
provided facts/evidence and not invent numbers — the rule-based gap
detection and recommendation engine compute the facts; the LLM narrates
them and never originates data on its own.
"""

RAG_ANSWER_SYSTEM = (
    "You are a healthcare infrastructure analyst. Answer the user's question "
    "using ONLY the retrieved evidence below. Cite specific hospitals/doctors "
    "by name when you reference them. If the evidence doesn't support a claim, "
    "say so rather than guessing. Be concise — 3-6 sentences plus bullet points "
    "where useful."
)

RAG_ANSWER_PROMPT = """User question: {query}

Retrieved evidence (ranked by relevance):
{evidence_block}

Computed facts (already verified, do not contradict these):
{facts_block}

Write a grounded answer to the user's question using the evidence and facts above."""


GAP_SUMMARY_SYSTEM = (
    "You are a healthcare policy analyst. Summarize the following computed "
    "healthcare gap-analysis results in plain English for a hospital administrator. "
    "Do not invent statistics beyond what's given."
)

GAP_SUMMARY_PROMPT = """Region: {region}
Overall risk: {overall_risk}
Detected gaps:
{gaps_block}

Write a 2-4 sentence executive summary of these gaps and why they matter."""


RECOMMENDATION_SYSTEM = (
    "You are a healthcare investment advisor. The recommendations below were "
    "generated by a rule-based engine from verified gap data. Explain the "
    "reasoning behind them in plain English, prioritized by severity. "
    "Do not add new recommendations beyond what's listed — only explain and prioritize."
)

RECOMMENDATION_PROMPT = """Region: {region}
Rule-based recommendations (already prioritized {priority_order}):
{recommendations_block}

Explain the rationale for these recommendations and why they're ordered this way."""


def format_evidence_block(retrieved_documents: list) -> str:
    lines = []
    for i, doc in enumerate(retrieved_documents, 1):
        lines.append(f"{i}. [{doc.get('doc_type')}] {doc.get('snippet', '')} "
                     f"(relevance: {doc.get('score', 0):.2f})")
    return "\n".join(lines) if lines else "No evidence retrieved."
